package ro.fiismart.ai.dto.response;

/**
 * One lecture inside an AI-generated course. Markdown body only (no
 * video/PDF in v1) — the professor adds richer media later via the
 * existing upload flow.
 *
 * <p>Generated by {@code CourseContentAiService} as part of
 * {@link GeneratedCourseDTO}. The body must be capped on the model side
 * (schema description: max 4000 chars) so a single oversized lecture
 * cannot blow our token budget when persisted.
 */
public record GeneratedLecture(
        String title,
        String content,
        Integer durationSecs
) {
}
