services:
  mongo:
    image: mongo:latest
    container_name: mongo-fiismart
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 5

  seeder:
    build: .
    container_name: java-seeder
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data: